A =input('Nama                 :')
B =input("NIM                  :")
C =input('Kelas Pararel        :')
D =input("Tempat/Tanggal Lahir :")
E =input("Alamat               :")
F =input('Hobby                :')
G =input('No.HP                :')
print("\nNama               :",A)
print("NIM                  :",B)
print("Kelas Pararel        :",C)
print("Tempat/Tanggal Lahir :",D)
print("Alamat               :",E)
print("Hobby                :",F)
print("No.HP                :",G)