print("########       #       #\n")
print("#      #        #     #\n")
print("#      #         #   #\n")
print("#   #  #          # #\n")
print("#    # #           #\n")
print("########           #\n")
print("        #          #\n")
print("         #         #")