a,b,i,j,x,y =(input(" ")).split()
Hasil = (int (a) - int (b))*int (i)/int (j)-(int (x)+int (y))
print("{:.3f}\n".format(Hasil))
a,b =(input(" ")).split()
i,j =(input(" ")).split()
x,y =(input(" ")).split()
Hasil = (int (a) - int (b))*int (i)/int (j)-(int (x)+int (y))
print("{:.3f}".format(Hasil))